### ISSUE TITLE
pretrained weight

### ISSUE THREAD

**Issue by macTracyHuang** [RyanWangZf/MedCLIP#15]
hi, may i ask if mode.from_pretrained does download a checkpoint that is pretrained on ROCO?
coz I found the model cannot even differentiate a dog from an x-ray image

thx

**Comment by RyanWangZf** [comment]
no. it was pretrained on chexpert and mimic-cxr. Please refer to our paper: https://arxiv.org/pdf/2210.10163.pdf. The one you mention is another medclip: https://github.com/Kaushalya/medclip
