### ISSUE TITLE
Some questions about the test code

### ISSUE THREAD

**Issue by Eldo-rado** [RyanWangZf/MedCLIP#21]
👋Hi!  Thanks for your code, and I have a question to confirm.
When I run "As simple as using CLIP" in Readme, I try to output the values in the **inputs**, but I find that the values in the 'pixel_values' matrix are exactly the same (as shown in Figure 1), I wonder if this is normal? What causes this ?

![299f520756addc314b6ccf440a066682](https://user-images.githubusercontent.com/128444206/227257583-b0f7a216-efa6-4987-b39a-158382654a37.png)

**Comment by RyanWangZf** [comment]
Hi, are all values the same or just many -2.0976 ? This may be caused by the normalization where 0 are transformed to this value.

**Comment by Eldo-rado** [comment]
> Hi, are all values the same or just many -2.0976 ? This may be caused by the normalization where 0 are transformed to this value.

Thank you for your timely reply, which has completely solved my question.
It just many -2.0976, not all values. I didn't consider the same pixel of background and the effect of normalization.
Thanks again
